#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""Name:      massstab
   Date:      18.12.22
   Kurs:      Advent of Code
   Topic:     Grove Positioning System a
"""
import numpy as np

with open("data/input_test.txt") as f:
    data = f.read().splitlines()

encrypted = [int(i) for i in data]

print(encrypted)
instructions = encrypted.copy()
chase = list(range(len(instructions)))

div = len(instructions)



for orig_idx, instr in enumerate(instructions):
    shift = instr
    if shift < 0 and abs(shift) >= chase[orig_idx]:
        shift -= 1
    popped = encrypted.pop(chase[orig_idx])
    encrypted.insert((chase[orig_idx] + shift) % div, popped)
    tmp = chase.copy()
    popped_idx = chase.pop(chase.index(orig_idx))
    chase.insert((tmp[orig_idx] + shift) % div, popped_idx)

    # [0, 1, 4, 2, 3, 5, 6]

    print(encrypted)




