#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""Name:      massstab
   Date:      18.12.22
   Kurs:      Advent of Code
   Topic:     Grove Positioning System a/b
"""

# This solution is basically from reddit user Red__Pixel. After hours of trying I peeked at this solution.

with open("data/input.txt") as f:
    data = f.read().splitlines()

solution = 'b'

if solution == 'a':
    instructions = [int(i) for i in data]
if solution == 'b':
    instructions = [int(i) * 811589153 for i in data]
chase = list(range(len(instructions)))
div = len(instructions)

for _ in range(10):
    for orig_idx, instr in enumerate(instructions):
        pop_idx = chase.index(orig_idx)
        popped = chase.pop(pop_idx)
        chase.insert((pop_idx + instructions[orig_idx]) % len(chase), orig_idx)
    if solution == 'a':
        break

start = chase.index(instructions.index(0))
print(sum(instructions[chase[(start + i) % len(chase)]] for i in [1000, 2000, 3000]))
